### ISSUE TITLE
downsampleMatrix/downsampleReads and Seurat normalisation

### ISSUE THREAD

**Issue by lc822** [MarioniLab/DropletUtils#24]
Hi,

I am performing combined analysis of three scRNA-seq samples using Cell Ranger and Seurat.   I am trying to understand the purpose of downsampling the matrix/reads with DropletUtils if you are then going to normalize for cell sequencing depth within the sctransform step in Seurat?  Is there any advantage to performing both of these normalization steps or would you perform one or the other?  In what situations would DropletUtils downsampling be advantageous over Seurat normalization and vice versa?

Many thanks,
Lucy

**Comment by LTLA** [comment]
Many people hate downsampling, and actually, I'm one of them. We always have to downsample to the coverage of the lowest batch (or cell, sample, or whatever), which means that we're throwing away information deliberately. And that just sucks. So, I have always scaled and log-transformed (see `scater::logNormCounts()` for cells, and `batchelor::multiBatchNorm()` for batches).

That said, scaling has problems of its own because it doesn't properly capture the fact that a normalized expression value derived from a high count has a lower variance than the same expression value derived from a low count. This can (very rarely) cause problems like those discussed [here](https://osca.bioconductor.org/normalization.html#applying-the-size-factors). And, for all my distaste for downsampling, it is the best solution in this case, because you _need_ to throw away information in the high-coverage cells to match those of the low-coverage cells.

Now, onto _sctransform_. It aims to solve that variance problem that I discussed above, and it does a pretty good job of it in some scenarios. However, the calculation of the Pearson residuals re-introduces other (related) problems that are discussed [here](https://ltla.github.io/SingleCellThoughts/general/transformation.html#3_handling_differences_in_library_size) (though the entire document is worth reading for understanding why we transform in the first place). I suspect that the same issues apply to the corrected UMI counts, as these are obtained by reversing the construction of the residuals.

AFAIK, the _Seurat_ workflow only uses _sctransform_ for feature selection, and it still relies on scaling and log-transformation for the downstream analysis. IMO this is unnecessarily convoluted - we just do our feature selection directly on the log-values - but I guess it's fine.

**Comment by LTLA** [comment]
I'm going to assume that your problem was solved.

**Comment by lc822** [comment]
Thank you for the detailed response.  I am still trying to get my head around this.  My question is, why can't we treat cells from different batches the same way as we treat cells within a batch and normalise for sequencing depth using e.g. sctransform, logNormCounts?  Shouldn't this account for any differences in sequencing depth between the cells (irrespective of whether they are in different batches)?

**Comment by LTLA** [comment]
Because sequencing depth isn't the only difference. For example, you might have:

- Differences in biology **that you don't care about**; maybe the incubator was slightly warmer and this increased the expression of certain genes. Or an overnight incubation ran for an extra hour and that resulting in more differentiation. Or you're collecting samples from genetically different donors. Or whatever, it's just a difference that you want to get rid of, because if you didn't, you would have to interpret 20 batch-specific clusters rather than just 5.
- Differences in technology. Maybe one batch was generated with Smart-seq2 and the other batch was generated with 10X, so you have a big read vs UMI difference that isn't just a global difference in sequencing depth. For example, long genes will have more reads while UMIs are (in theory) much less dependent on the gene length, causing gene-specific differences. A milder example might be the difference between the 5' vs 3' 10X protocols, which presumably have a different set of biases that favor transcripts with different biophysical properties.
- More technical differences. Even with the same biological system and technology, you can easily get run-to-run variation depending on the reagent quality, how the machine is feeling at any given point in time, etc. Ribosomal protein genes seem to be the biggest offender, as they are often more variable across batches than they are within batches. I speculate that this is because they are short and abundant so are most sensitive to any fluctuations to capture efficiency.

**Comment by lc822** [comment]
I understand these differences and that they can be dealt with using batch correction tools such as Harmony and CCA.  But how does downsampling/multiBatchNorm help deal with these specific batch effects?  If you want to merge multiple similar batches and only account for differences in sequencing depth, why would you downsample with e.g. cellranger aggr and then run sctransform, instead of just running sctransform directly?

**Comment by LTLA** [comment]
Because of the variance. Downsampling adds noise so that the batches match up in terms of their variability. This is important as it also affects the location after log-transformation. Consider the following scenario, where we have two batches that only differ in coverage:

```r
set.seed(10000)

# Mocking up a simulation.
ngenes <- 10000
ncells <- 1000

# Mostly non-DE genes, but first 100 genes are strongly DE.
means <- matrix(2^rnorm(ngenes), nrow=ngenes, ncol=ncells)
means[1:100,1:500] <- means[1:100,1:500] * 10

# 10-fold difference in coverage between batches, but same means.
batch1 <- matrix(rpois(length(means), lambda=means/2), ncol=ncells)
batch2 <- matrix(rpois(length(means), lambda=means*5), ncol=ncells)

combined <- cbind(batch1, batch2)
```

Let's do some log-normalization based on the library size. We make a PCA plot where the color is the cell type and the point type is the batch. Ideally, we should see two blobs of different color.

```r
library(scater)
combined.norm <- normalizeCounts(combined, size_factors=librarySizeFactors(combined))

library(BiocSingular)
pca.norm <- runPCA(t(combined.norm), rank=2, BSPARAM=bsparam())

celltype <- rep(rep(1:2, each=500), 2)
batch.id  <- rep(1:2, each=1000)
plot(pca.norm$x[,1], pca.norm$x[,2], col=celltype, pch=batch.id)
```

![lognorm](https://user-images.githubusercontent.com/8166669/67033476-b4452080-f0ca-11e9-894f-c875f4f8de9c.png)

Okay, that sucked. This is due to the fact that the mean log is not the same as the log-mean, and the difference depends on the variance; so if the batches have different variance, the log-transformation re-introduces the difference in coverage _even after normalization has been performed!_ I discuss this in more detail [here](https://www.biorxiv.org/content/10.1101/404962v1).

Well, what about **sctransform**?

```r
library(sctransform)
rownames(combined) <- seq_len(nrow(combined))
colnames(combined) <- seq_len(ncol(combined))
vst.out <- vst(combined+0) # doesn't like integers.

pca.vst <- runPCA(t(vst.out$y), rank=2, BSPARAM=bsparam())
plot(pca.vst$x[,1], pca.vst$x[,2], col=celltype, pch=batch.id)
```

![vst](https://user-images.githubusercontent.com/8166669/67033543-d8086680-f0ca-11e9-9e29-aacc2acd0224.png)

Better, but still not good. The problem here is technically different but still relates to how the mean-variance relationship is handled, see [here](https://ltla.github.io/SingleCellThoughts/general/transformation.html) for details. 

And that brings us to downsampling:

```r
combined.down <- normalizeCounts(combined, size_factors=librarySizeFactors(combined), downsample=TRUE)
pca.down <- runPCA(t(combined.down), rank=2, BSPARAM=bsparam())
plot(pca.down$x[,1], pca.down$x[,2], col=celltype, pch=batch.id)
```

![down](https://user-images.githubusercontent.com/8166669/67033653-156cf400-f0cb-11e9-83ae-af29e0c3ba8b.png)

This works, as the variances are now forced to match across batches.

**Comment by lc822** [comment]
Thank you for the really clear explanation - this is very helpful!
