### ISSUE TITLE
R 3 Compatabiilty?

### ISSUE THREAD

**Issue by ColeWunderlich** [MarioniLab/DropletUtils#53]
Hello, I noticed the Bioconductor release for R3.6 (Bioc 3.10) only has DropletUtils `1.6.1`  is there any plan to update Bioc 3.10 to the newer version?  Or does the latest version have some R4.x specific code?

**Comment by LTLA** [comment]
The very latest version of **DropletUtils** (1.9.15) will be part of the BioC 3.12 release that's happening next week. That release will require R 4.0 to work; no guarantees are provided for any lower version of R.

Now, I don't recall any 4-specific code in **DropletUtils**, so you could - in theory - try to install it on R 3.6. But you would be taking matters into your own hands, and if something goes wrong, all I can do is shrug and suggest that you upgrade R and try again.

As for the more general question of "why does BioC 3.12 mandate R 4+ in the first place?", it is a good idea to have a look at the myriad changes in the [R NEWS file](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html). Some of these are big:

> R now uses a stringsAsFactors = FALSE default, and hence by default no longer converts strings to factors in calls to data.frame() and read.table().
>
> A large number of packages relied on the previous behaviour and so have needed/will need updating.

Some a bit more specific, but still required nonetheless by various packages I maintain:

> A server socket connection, a new connection type representing a listening server socket, is created via serverSocket() and can accept multiple socket connections via socketAccept().

And some of which are just nice to have:

> The palette() function has a new default set of colours (which are less saturated and have better accessibility properties). 

On a developer level, it is much easier to program against a single R version rather than requiring branched behavior to handle multiple versions. And on a project level, it is much easier to tell all users to upgrade R to the latest version, than it is to allow individual developers and users to make (possibly contradicting) decisions on the minimum R dependencies.

**Comment by ColeWunderlich** [comment]
Hello Aron, I just realized I never replied to this.

For any users still on `R 3` I can confirm that DropletUtils `1.9.15` ran without issue for me on `R 3.6`. (Although I will say I did not thoroughly stress test it)
