### ISSUE TITLE
read10xCounts doesn't work with StarSolo output

### ISSUE THREAD

**Issue by raivivek** [MarioniLab/DropletUtils#77]
Hi, it appears that in latest version, there is a hard requirement in the code that the `features.tsv` file have 3 columns. The StarSolo output contains two columns (`ID` and `Symbol`), at least in my case, and this results in error.

The culprit line is here:
https://github.com/MarioniLab/DropletUtils/blob/a9118d5ae8e266faccc910127ff69bc12cf6b395/R/read10xCounts.R#L219

I'm not sure if this a problem with my STAR run or an assumption by the package that only holds for output strictly from 10X pipeline. In any case, modifying the code so that it works based on the number of columns it detects in the file would solve this problem. Let me know what you think.

**Comment by LTLA** [comment]
I'm not familiar with STARsolo's output format, but `read10xCounts` was pretty much designed solely for Cellranger outputs, so there's not much guarantee that it would work for anything else. If STARsolo is mimicking Cellranger's output format, then you might have a shot - I would suggest trying with `version = "2"`, which only expects two columns in `features.tsv`.

**Comment by raivivek** [comment]
Thanks for your response. Unfortunately, it appears that 10X CellRanger output is also quite variable in its result. For example, here is a snippet of the `features.tsv` generated by the CellRanger pipeline from 10X for one of our analyses. As you can see, in this case the file actually has 5 columns. As a result, I'm not if a fixed 3-column structure is specified by the spec or just dependent on the annotation files used with the pipeline. I believe just adding another argument called `feature.col.names` or something like that should give enough flexibility to work by default and still allow people like me to work with package without modifying the source.

```
 ENSG00000243485 MIR1302-2HG     Gene Expression chr1    29553   30267
 ENSG00000237613 FAM138A Gene Expression chr1    36080   36081
 ENSG00000186092 OR4F5   Gene Expression chr1    65418   69055
 ENSG00000238009 AL627309.1      Gene Expression chr1    120931  133723
...
```

**Comment by LTLA** [comment]
Hm. This must be one of the newer CellRanger versions. It does remind me of a file that I saw elsewhere this week, and I was wondering where those extra columns were coming from. So based on this, I assume CellRanger itself is adding them.

If it's going to be like that, I would prefer to auto-detect it and cast the coordinates into a `GRanges`. Try out #79 and see whether that works for you. It will probably work for your original question as it just names the columns according to their availability, i.e., 2 columns will result in ID + Symbol, 3 columns will be ID + Symbol + Type, 6 columns will be that + chromosomal position.

**Comment by raivivek** [comment]
Thanks! Sure, that should work for me. However, one thing that I wanted to mention is that I am not sure if we can assume the columns to be ordered in a specific manner (of if there is a limit to the number of columns at all) .

**Comment by LTLA** [comment]
At some point, there must be some minimal expectations on what the "10X format" is, otherwise the function will struggle to do anything useful. For example, the function currently expects an `ID` field to use to set the rownames; similarly `Chromosome`, `Start` and `End` to cast coordinates to `GRanges`. If there are more columns, or they occur in some arbitrary order, then I'd argue that we're not dealing with 10X-formatted data anymore. At that point, all bets are off and people might as well just construct the SCEs themselves after doing `readMM` + `read.delim` to read everything into memory.

In the specific case of STARsolo; `read10xCounts()` would only be appropriate if STARsolo promises to deliver 10X-formatted files. This promise already seems like it hasn't really been met, based on the lack of a [third column in `features.tsv.gz`](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/matrices) - so `read10xCounts()` has no real obligation to work here, and the change in #79 is simply a courtesy on my behalf. If the STARsolo output continues to diverge from the expectations of the 10X format, then `read10xCounts()` will become less and less suitable. One could imagine writing a `readStarSolo()` function but I don't work enough with STARsolo output to be bothered to do it myself. Perhaps @jonathangriffiths may have an opinion.

**Comment by raivivek** [comment]
I think it's fair for you to prioritize maintaining compatibility with 10X output since, as you mentioned, the function is called `read10xCounts` and not `readStarSolo`. PR #79 is a welcome change for now. Thanks!

**Comment by samleenz** [comment]
Hi! While this PR (#79) makes sense I've found it's caused an issue for me in loading a 10x dataset I'm currently working on. 

It is an issue with the specification of the features.tsv.gz file in the data I'm using (a tab between "Gene" and "Expression" where there should be a space (see below)). In version 1.14.0 it read the files fine and then I fixed the unintended split of the column in R but now with 1.14.1 the `read10xCounts()` function fails with an error, which happens when `GRanges()` is called.  

 I'll fix the features.tsv.gz files for this data-set so it's not an immediate issue but I just wanted to flag it with you in case it was a potential problem going forward for other peoples data. 


```
---- ---- % gunzip -c features.tsv.gz | head
ENSG00000243485	MIR1302-2HG	Gene	Expression
ENSG00000237613	FAM138A	Gene	Expression
ENSG00000186092	OR4F5	Gene	Expression
ENSG00000238009	AL627309.1	Gene	Expression
ENSG00000239945	AL627309.3	Gene	Expression
ENSG00000239906	AL627309.2	Gene	Expression
ENSG00000241599	AL627309.4	Gene	Expression
ENSG00000236601	AL732372.1	Gene	Expression
ENSG00000284733	OR4F29	Gene	Expression
ENSG00000235146	AC114498.1	Gene	Expression
```

Thanks,
Sam
