### ISSUE TITLE
downsampleReads error

### ISSUE THREAD

**Issue by harshini-c** [MarioniLab/DropletUtils#89]
Hi,

I just installed DropletUtils with R version 4.2.0 and Bioconductor 3.15

I wanted to downsample my 10x scRNAseq matrix from one condition. However, i get the following error:

`Error in get_cell_barcodes(sample, "barcode", barcode.length) : 
  c++ exception (unknown reason)`

Could you please let me know how to resolve this?

I am attaching a screenshot of the error here as well.

Thank you!
<img width="636" alt="image" src="https://user-images.githubusercontent.com/78223419/179087921-0063800f-7c40-476b-b7b1-28eb1be1d231.png">

**Comment by jonathangriffiths** [comment]
The release DropletUtils is building fine and the tests include this function, alongside loading of the molecule info data. In your case, you seem to have a problem with data loading rather than with the downsampling itself. Please could you check if your file actually exists, or if it has been otherwise broken in some way? For instance, can you load it with `read10xMolInfo`?

**Comment by LTLA** [comment]
`?downsampleReads`:

```
Arguments:

 sample: A string containing the path to the molecule information HDF5
          file.
```

https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/molecule_info

`?read10xCounts`:

```
Arguments:

 samples: ...

          Alternatively, each string may contain a path to a HDF5 file
          in the sparse matrix format generated by 10X. These can be
          mixed with directory names when ‘type="auto"’.

          ...
```

https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/advanced/h5_matrices

**Comment by harshini-c** [comment]
Thank you.

This is what i tried

```
test <- read10xCounts('./scRNAseq_Neu_WT/outs/filtered_feature_bc_matrix.h5')

downsampled_test <- downsampleMatrix(counts(test),prop=0.5)
```

I had two conditions and the read depth for one condition per cell was half the other condition. So my goal was to downsample. Please let me know if this would be the correct approach. 

Thank you for all your help as i try to understand this!

**Comment by jonathangriffiths** [comment]
That ought to have successfully downsampled the matrix that you loaded. If you are loading the data from your other sample in the same way, then it sounds like it should have achieved what you wanted. I'm glad this has helped (though in future, please raise analysis questions on the bioconductor support site rather than here)

**Comment by harshini-c** [comment]
Thank you very much for your quick response and help in this regard! Appreciate it.
