### ISSUE TITLE
Remove genes not detected in any cell barcode

### ISSUE THREAD

**Issue by hongduosun** [MarioniLab/DropletUtils#91]
Hi, will emptyDrops automatically remove genes not detected in any cell barcode? or have to remove them manually before calling the function?

**Comment by jonathangriffiths** [comment]
emptyDrops should not remove these genes.

Furthermore I would not recommend that you remove them, as this represents a loss of information in your dataset (a downstream user cannot know why you removed that gene, and whether it was undetected, lowly detected, or for any other reason).

**Comment by hongduosun** [comment]
Thanks for the reply, and sorry, I mean genes that are not detected in all barcodes.

From the manuscript of emptyDrops:
> **Description of the method**
**Testing for deviations from the ambient profile**
.....
(We assume that any gene with counts of zero for all barcodes has already been filtered out, as this provides no information for distiguishing between barcodes.)
......

Should I remove them?

**Comment by LTLA** [comment]
Both of you are half right.

Internally, `emptyDrops` will automatically remove genes with total counts of zero across all barcodes - it calls `.compute_ambient_stats`, which discards all-zero rows prior to further analysis:

https://github.com/MarioniLab/DropletUtils/blob/0632cfa899bba03228e20c5785f14b170b38fa03/R/ambientProfileEmpty.R#L113-L116

We do this because the Good-Turing algorithm will infer non-zero proportions when the count for a gene in the ambient profile is zero. This is necessary to deal with cases where the ambient profile has a zero count for a gene but a cell has a non-zero count, otherwise you'd end up with a likelihood of negative infinity for that cell's count vector. However, it seems wrong to create a non-zero proportion for genes that will never have a non-zero count, anywhere, e.g., pseudo-genes, predicted genes, other kinds of nonsense. So `emptyDrops` will just remove them automatically before proceeding with the p-value calculations.

Of course, `emptyDrops` doesn't actually return the filtered count matrix, it just returns statistics that allow you to decide how to filter your matrix. At this point, Jonny's advice is generally applicable. At work, I did a fair amount of data integration, and the inconsistencies in feature sets between datasets - even those nominally aligned to the same genome! - drove me up the wall. Do I ignore genes that aren't present in all datasets? Do I fill them in with zeros? Is that safe? Who knows?

**Comment by hongduosun** [comment]
I'm sorry I didn't describe the question clearly. It is only limited to the cell calling step and getting the statistics to decide which cells are non-ambient, I do not intend to remove any features/genes in the final filtered matrix.

Thanks for clarifying, it helps a lot!
